token: 5276786543:AAGd-RhyWSQrbrVDHk2WxVERHhJiChzbW1U #BookGitalBot
admins: 
  - 127529747
  - 127876
mainloop_timer: 5
advice_timer: 604800 # 7 days in seconds = 604800
re_invitation_timer: 259200 # 3 days in seconds = 259200

books:
  - id: glaz-volka
    name: '¬´–ì–ª–∞–∑ –≤–æ–ª–∫–∞¬ª –î–∞–Ω–∏—ç–ª—å –ü–µ–Ω–Ω–∞–∫'
    file: media/glaz-volka.pdf
    tags:
      - –¥—Ä—É–∂–±–∞
    description: '–í–æ–ª—á—å—è —Å—Ç–∞—è –±–µ–∂–∏—Ç –æ—Ç –±—Ä–∞–∫–æ–Ω—å–µ—Ä–æ–≤. –í –ø–æ–ø—ã—Ç–∫–µ —Å–ø–∞—Å—Ç–∏ —Å–≤–æ—é —Å–µ—Å—Ç—Ä—É –ì–æ–ª—É–±–æ–π –≤–æ–ª–∫ —Å–∞–º –ø–æ–ø–∞–¥–∞–µ—Ç –≤ –ª–æ–≤—É—à–∫—É. –¢–µ–ø–µ—Ä—å –æ–Ω –∂–∏–≤–µ—Ç –≤ –∑–æ–æ–ø–∞—Ä–∫–µ, –≥–¥–µ –∏ –∑–Ω–∞–∫–æ–º–∏—Ç—Å—è —Å –ê—Ñ—Ä–∏–∫–æ–π, —Å—Ç—Ä–∞–Ω–Ω—ã–º –º–∞–ª—å—á–∏–∫–æ–º —Å —É–¥–∏–≤–∏—Ç–µ–ª—å–Ω–æ–π –∏—Å—Ç–æ—Ä–∏–µ–π.
      
    ¬´–ì–ª–∞–∑ –≤–æ–ª–∫–∞¬ª ‚Äî —Å–∫–∞–∑–∫–∞ –ø—Ä–æ –¥—Ä—É–∂–±—É –∏ –ø—Ä–µ–¥–∞–Ω–Ω–æ—Å—Ç—å. –ì–ª–∞–≤–Ω—ã–µ –≥–µ—Ä–æ–∏, –º–∞–ª—å—á–∏–∫ –ø–æ –∏–º–µ–Ω–∏ –ê—Ñ—Ä–∏–∫–∞ –∏ –ø–æ–ª—è—Ä–Ω—ã–π –≤–æ–ª–∫, –ø—Ä–æ—à–ª–∏ —á–µ—Ä–µ–∑ –º–Ω–æ–∂–µ—Å—Ç–≤–æ –∏—Å–ø—ã—Ç–∞–Ω–∏–π: –ø–æ—Ç–µ—Ä—è–ª–∏ —Å–µ–º—å—é, –¥–æ–º, –¥—Ä—É–∑–µ–π, —Å–≤–æ–±–æ–¥—É. –û–Ω–∏ –æ—á–µ–Ω—å –ø–æ—Ö–æ–∂–∏, –∏ –ø–æ—ç—Ç–æ–º—É —Ç–∞–∫ –Ω—É–∂–Ω—ã –¥—Ä—É–≥ –¥—Ä—É–≥—É.
      
    –í —ç—Ç–æ–π –∫–Ω–∏–≥–µ –ø—Ä–µ–∫—Ä–∞—Å–Ω—ã–π –¥–µ—Ç—Å–∫–∏–π –ø–∏—Å–∞—Ç–µ–ª—å, —à–∫–æ–ª—å–Ω—ã–π —É—á–∏—Ç–µ–ª—å –∏ –≥—É–º–∞–Ω–∏—Å—Ç –î–∞–Ω–∏—ç–ª—å –ü–µ–Ω–Ω–∞–∫ —Ä–∞—Å—Å–∫–∞–∑—ã–≤–∞–µ—Ç –æ —Å–æ–∑–∏–¥–∞—Ç–µ–ª—å–Ω–æ–π —Å–∏–ª–µ –Ω–∞–¥–µ–∂–¥—ã.
      
    <b>–ö–æ–º—É –ø–æ–Ω—Ä–∞–≤–∏—Ç—Å—è –∫–Ω–∏–≥–∞?</b>

    ‚Ä¢ –í—Å–µ–º, –∫—Ç–æ –ª—é–±–∏—Ç –ø—Ä–∏—Ä–æ–¥—É –∏ –∂–∏–≤–æ—Ç–Ω—ã—Ö. –í–æ–ª–∫–∏, –≤–µ—Ä–±–ª—é–¥—ã, –≥–∏–µ–Ω—ã, –æ–≤—Ü—ã ‚Äî –≤ —ç—Ç–æ–π —Å–∫–∞–∑–∫–µ –º–Ω–æ–≥–æ –≥–µ—Ä–æ–µ–≤!

    ‚Ä¢ –ü—É—Ç–µ—à–µ—Å—Ç–≤–µ–Ω–Ω–∏–∫–∞–º. –ö–∞–∫ –∑–¥–æ—Ä–æ–≤–æ, —á—Ç–æ –º–æ–∂–Ω–æ –ø–æ–±—ã–≤–∞—Ç—å –∏ –Ω–∞ –ø–æ–ª—è—Ä–Ω–æ–º —Å–µ–≤–µ—Ä–µ, –∏ –≤ –ê—Ñ—Ä–∏–∫–µ, —á–∏—Ç–∞—è –≤—Å–µ–≥–æ –æ–¥–Ω—É –∫–Ω–∏–≥—É.

    ‚Ä¢ –¢–µ–º, –∫–æ–º—É –Ω—É–∂–Ω–∞ –Ω–∞–¥–µ–∂–¥–∞!
      
    <b>–°—Å—ã–ª–∫–∏ –Ω–∞ –∫–Ω–∏–≥–∏</b>

    <a href="https://www.litres.ru/daniel-pennak/glaz-volka/chitat-onlayn/">–≠–ª–µ–∫—Ç—Ä–æ–Ω–Ω–∞—è –∫–Ω–∏–≥–∞</a>

    <a href="https://samokatbook.ru/catalog/knigi-shkolnik/knigi-samostoyatelnoe-chtenie/glaz-volka">–ü–µ—á–∞—Ç–Ω–∞—è –∫–Ω–∏–≥–∞</a>'
  - id: krolik-edvard
    name: ¬´–£–¥–∏–≤–∏—Ç–µ–ª—å–Ω–æ–µ –ø—É—Ç–µ—à–µ—Å—Ç–≤–∏–µ –∫—Ä–æ–ª–∏–∫–∞ –≠–¥–≤–∞—Ä–¥–∞¬ª –ö–µ–π—Ç –î–∏–ö–∞–º–∏–ª–ª–æ
    file: media/krolik-edvard.pdf
    tags:
      - –∏—Å—Ç–æ—Ä–∏–∏ –ø—Ä–æ –∂–∏–≤–æ—Ç–Ω—ã—Ö
    description: '–£ –≠–¥–≤–∞—Ä–¥–∞ –µ—Å—Ç—å –≤—Å–µ: –ª—é–±—è—â–∞—è —Ö–æ–∑—è–π–∫–∞, —É—é—Ç–Ω—ã–π –¥–æ–º, –∫—Ä–∞—Å–∏–≤—ã–µ –Ω–∞—Ä—è–¥—ã, –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å –ª—é–±–æ–≤–∞—Ç—å—Å—è —Å–≤–æ–∏–º –æ—Ç—Ä–∞–∂–µ–Ω–∏–µ–º. –û–Ω —Å—á–∞—Å—Ç–ª–∏–≤—ã–π —Ñ–∞—Ä—Ñ–æ—Ä–æ–≤—ã–π –∫—Ä–æ–ª–∏–∫, –∫–æ—Ç–æ—Ä—ã–π –¥–µ–ª–∞–µ—Ç —Å—á–∞—Å—Ç–ª–∏–≤–æ–π –º–∞–ª–µ–Ω—å–∫—É—é –ê–±–∏–ª–∏–Ω. –ù–æ –≤–æ—Ç –ø—Ä–æ–±–ª–µ–º–∞: –≠–¥–≤–∞—Ä–¥ –¥—É–º–∞–µ—Ç –ª–∏—à—å –æ —Å–µ–±–µ –∏ —Å–æ–≤—Å–µ–º –Ω–µ —É–º–µ–µ—Ç –ª—é–±–∏—Ç—å, –∞ –≤—Å–µ –∑–Ω–∞—é—Ç, —á—Ç–æ —Ö–æ—Ä–æ—à–∏—Ö –∏—Å—Ç–æ—Ä–∏–π –±–µ–∑ –ª—é–±–≤–∏ –Ω–µ –±—ã–≤–∞–µ—Ç.

    –ß–∏—Ç–∞—Ç–µ–ª–∏ —ç—Ç–æ–π –∫–Ω–∏–≥–∏ –≤–º–µ—Å—Ç–µ —Å –≠–¥–≤–∞—Ä–¥–æ–º –∑–∞–¥—É–º–∞—é—Ç—Å—è –æ —Ç–æ–º, –ø–æ—á–µ–º—É –º—ã –∫–æ–≥–æ-—Ç–æ –ª—é–±–∏–º, –∏ –∑–∞—á–µ–º –Ω–∞–º –≤–æ–æ–±—â–µ –∏—Å–ø—ã—Ç—ã–≤–∞—Ç—å —ç—Ç–æ —á—É–≤—Å—Ç–≤–æ, –æ—Ç–ø—Ä–∞–≤—è—Ç—Å—è –≤ —É–¥–∏–≤–∏—Ç–µ–ª—å–Ω–æ–µ –ø—É—Ç–µ—à–µ—Å—Ç–≤–∏–µ –∏ –ø–æ—Å–º–æ—Ç—Ä—è—Ç, –∫–∞–∫–æ–π —Ä–∞–∑–Ω–æ–π –º–æ–∂–µ—Ç –±—ã—Ç—å –ª—é–±–æ–≤—å.

    <b>–ö–æ–º—É –ø–æ–Ω—Ä–∞–≤–∏—Ç—Å—è –∫–Ω–∏–≥–∞?</b>

    ‚Ä¢ –õ—é–±–∏—Ç–µ–ª—è–º —Å–∫–∞–∑–æ–∫. –§–∞—Ä—Ñ–æ—Ä–æ–≤—ã–π –∫—Ä–æ–ª–∏–∫ –Ω–µ –º–æ–∂–µ—Ç —Ö–æ–¥–∏—Ç—å –∏ –≥–æ–≤–æ—Ä–∏—Ç—å, –Ω–æ —É –Ω–µ–≥–æ –µ—Å—Ç—å –≤–Ω—É—Ç—Ä–µ–Ω–Ω–∏–π –º–∏—Ä.

    ‚Ä¢ –¢–µ–º, –∫—Ç–æ –≤–µ—Ä–∏—Ç, —á—Ç–æ –µ–≥–æ –∏–≥—Ä—É—à–∫–∏ –∂–∏–≤—ã–µ.

    <b>–°—Å—ã–ª–∫–∞ –Ω–∞ –∫–Ω–∏–≥—É:</b>

    <a href="https://www.chitai-gorod.ru/catalog/book/352908/">–ü–µ—á–∞—Ç–Ω–∞—è –∫–Ω–∏–≥–∞</a>'
  - id: priklucheniya-kamo
    name: ¬´–ü—Ä–∏–∫–ª—é—á–µ–Ω–∏—è –ö–∞–º–æ¬ª –î–∞–Ω–∏—ç–ª—å –ü–µ–Ω–Ω–∞–∫
    file: media/priklucheniya-kamo.pdf
    tags:
      - —Ñ–∞–Ω—Ç–∞–∑–∏–∏
    description: '–í —ç—Ç–æ–π –∫–Ω–∏–≥–µ –≤—Å–µ —Å–∞–º—ã–µ –ø—Ä–µ–∫—Ä–∞—Å–Ω—ã–µ –º–µ—á—Ç—ã –±—É–¥—É—â–µ–≥–æ –ø—è—Ç–∏–∫–ª–∞—Å—Å–Ω–∏–∫–∞ –∏ –≤—Å–µ –µ–≥–æ —Å–∞–º—ã–µ –±–æ–ª—å—à–∏–µ —Å—Ç—Ä–∞—Ö–∏.
     
    –ö–∞–∫ –ø–æ–¥–≥–æ—Ç–æ–≤–∏—Ç—å—Å—è –∫ –ø–µ—Ä–µ—Ö–æ–¥—É –≤ —Å—Ä–µ–¥–Ω—é—é —à–∫–æ–ª—É –∏ –ø—Ä–∏–≤—ã–∫–Ω—É—Ç—å –∫ —Ä–∞–∑–Ω—ã–º —É—á–∏—Ç–µ–ª—è–º? –ö–∞–∫ –ø—Ä–∏–≤—ã–∫–Ω—É—Ç—å –∫ –Ω–æ–≤—ã–º —Ç—Ä–µ–±–æ–≤–∞–Ω–∏—è–º –∏ –æ—Ç–≤–µ—Ç—Å—Ç–≤–µ–Ω–Ω–æ—Å—Ç–∏? –≠—Ç–∞ –∫–Ω–∏–∂–∫–∞ –ø—Ä–æ –≤–∑—Ä–æ—Å–ª–µ–Ω–∏–µ: –∏–Ω–æ–≥–¥–∞ –æ—á–µ–Ω—å –Ω–µ–∑–∞–º–µ—Ç–Ω–æ–µ, –∞ –∏–Ω–æ–≥–¥–∞ —Å–æ–≤—Å–µ–º —Ä–µ–∑–∫–æ–µ.
     
    ¬´–ü—Ä–∏–∫–ª—é—á–µ–Ω–∏—è –ö–∞–º–æ¬ª ‚Äî —Å–±–æ—Ä–Ω–∏–∫ –≤–µ—Å–µ–ª—ã—Ö –ø–æ–≤–µ—Å—Ç–µ–π –î–∞–Ω–∏—ç–ª—è –ü–µ–Ω–Ω–∞–∫–∞. –ï–≥–æ –∑–¥–æ—Ä–æ–≤–æ —á–∏—Ç–∞—Ç—å –≤—Å–ª—É—Ö, —Ä–∞–∑—ã–≥—Ä—ã–≤–∞—è –¥–∏–∞–ª–æ–≥–∏ –∏ –Ω–∞–¥—Ä—ã–≤–∞—è –∂–∏–≤–æ—Ç–∏–∫–∏ –æ—Ç —Ö–æ—Ö–æ—Ç–∞.
     
    <b>–ö–æ–º—É –ø–æ–¥–æ–π–¥–µ—Ç —ç—Ç–∞ –∫–Ω–∏–≥–∞?</b>

    ‚Ä¢ –°–º–µ—à–ª–∏–≤—ã–º —Ä–µ–±—è—Ç–∞–º.

    ‚Ä¢ –ë—É–¥—É—â–∏–º –ø—è—Ç–∏–∫–ª–∞—Å—Å–Ω–∏–∫–∞–º, –æ–∂–∏–¥–∞—é—â–∏–º –Ω–æ–≤—É—é —à–∫–æ–ª—å–Ω—É—é –∂–∏–∑–Ω—å.

    ‚Ä¢ –§–∞–Ω—Ç–∞–∑–µ—Ä–∞–º –∏ –≤—ã–¥—É–º—â–∏–∫–∞–º. –ò–º–µ–Ω–Ω–æ —Ç–∞–∫ –º–æ–∂–Ω–æ –Ω–∞–∑–≤–∞—Ç—å –≥–ª–∞–≤–Ω—ã—Ö –≥–µ—Ä–æ–µ–≤.

    <b>–°—Å—ã–ª–∫–∞ –Ω–∞ –∫–Ω–∏–≥—É:</b>

    <a href="https://www.chitai-gorod.ru/catalog/book/1263996/?utm_source=google&utm_medium=cpc&utm_campaign=g_performance-max_rf&utm_term=&utm_content=g%7Cposition%7Cx%7C%7C%7Cad%7C%7C%7Cdevice%7Cc%7Cgeo%7C%7C9047022%7Ccid%7C15699221669%7Cgid%7C%7C&gclid=CjwKCAiA6Y2QBhAtEiwAGHybPa3AivqqWT7YrzCAXMQP-MtkGPL-OW-TA6337kAJcqBluUyi9ReKzxoCNAsQAvD_BwE">–ü–µ—á–∞—Ç–Ω–∞—è –∫–Ω–∏–≥–∞</a>'    
  - id: tonya-glimmerdal
    name: ¬´–¢–æ–Ω—è –ì–ª–∏–º–º–µ—Ä–¥–∞–ª¬ª –ú–∞—Ä–∏—è –ü–∞—Ä—Ä
    file: media/tonya-glimmerdal.pdf
    tags:
      - –æ –≥–µ—Ä–æ—è—Ö –¥–µ–≤–æ—á–∫–∞—Ö
    description: '–¢–æ–Ω—è ‚Äî –≤–µ—Å–µ–ª–∞—è, —è—Ä–∫–∞—è –∏ —ç–Ω–µ—Ä–≥–∏—á–Ω–∞—è –¥–µ–≤–æ—á–∫–∞. –¢–∞–∫–∏—Ö –≥–µ—Ä–æ–∏–Ω—å –º–∞–ª–æ –≤ –ª–∏—Ç–µ—Ä–∞—Ç—É—Ä–µ, –ø–æ—ç—Ç–æ–º—É –∫–Ω–∏–≥–∞ –ú–∞—Ä–∏–∏ –ü–∞—Ä—Ä —Å—Ä–∞–∑—É –æ–±—Ä–∞—â–∞–µ—Ç –Ω–∞ —Å–µ–±—è –≤–Ω–∏–º–∞–Ω–∏–µ.

    –ö–∞–∫ –∏ –≤ –ª—é–±–æ–π –±–æ–ª—å—à–æ–π –∫–Ω–∏–∂–∫–µ, –≤ –ø–æ–≤–µ—Å—Ç–∏ ¬´–¢–æ–Ω—è –ì–ª–∏–º–º–µ—Ä–¥–∞–ª¬ª –º–Ω–æ–∂–µ—Å—Ç–≤–æ —Ç–µ–º: –¥—Ä—É–∂–±–∞, –≤–∑–∞–∏–º–æ–æ—Ç–Ω–æ—à–µ–Ω–∏—è –≤ —Å–µ–º—å–µ, –¥–µ—Ä–µ–≤–µ–Ω—Å–∫–∞—è –∂–∏–∑–Ω—å, –≤–∑—Ä–æ—Å–ª–µ–Ω–∏–µ. –ï—Å—Ç—å –æ —á–µ–º –ø–æ–≥–æ–≤–æ—Ä–∏—Ç—å! –≠—Ç–∞ –∫–Ω–∏–≥–∞ –ø–æ–¥–æ–π–¥–µ—Ç –æ–ø—ã—Ç–Ω—ã–º —á–∏—Ç–∞—Ç–µ–ª—è–º, –∫–æ—Ç–æ—Ä—ã–º –∏–Ω—Ç–µ—Ä–µ—Å–Ω–æ —Å–ª–µ–¥–∏—Ç—å –∑–∞ —Ä–∞–∑–≤–∏—Ç–∏–µ–º —Å—é–∂–µ—Ç–∞ –∏ —Ä–∞—Å–∫—Ä—ã—Ç–∏–µ–º –ø–µ—Ä—Å–æ–Ω–∞–∂–µ–π.

    <b>–ö–æ–º—É –ø–æ–Ω—Ä–∞–≤–∏—Ç—Å—è —ç—Ç–∞ –∫–Ω–∏–≥–∞?</b>

    ‚Ä¢ –î–µ–≤—á–æ–Ω–∫–∞–º, —É—Å—Ç–∞–≤—à–∏–º —á–∏—Ç–∞—Ç—å –ø—Ä–æ –º–∞–ª—å—á–∏—à–µ–∫!

    ‚Ä¢ –ß—É—Ç–∫–∏–º –¥–µ—Ç—è–º, –∫–æ—Ç–æ—Ä—ã–µ –ª—é–±—è—Ç –¥—Ä—É–∂–∏—Ç—å.

    ‚Ä¢ –¢–µ–º, –∫—Ç–æ –∂–∏–≤–µ—Ç –∏–ª–∏ –º–µ—á—Ç–∞–µ—Ç –∂–∏—Ç—å –≤ –º–∞–ª–µ–Ω—å–∫–æ–º –≥–æ—Ä–æ–¥–∫–µ.

    <b>–°—Å—ã–ª–∫–∏ –Ω–∞ –∫–Ω–∏–≥–∏:</b>

    <a href="https://samokatbook.ru/catalog/knigi-shkolnik/knigi-o-seme/tonya-glimmerdal/">–ü–µ—á–∞—Ç–Ω–∞—è –∫–Ω–∏–≥–∞</a>

    <a href="https://www.litres.ru/mariya-parr/tonya-glimmerdal/chitat-onlayn/">–≠–ª–µ–∫—Ç—Ä–æ–Ω–Ω–∞—è –∫–Ω–∏–≥–∞</a>'
  - id: kot-ubiitsa
    name: ¬´–î–Ω–µ–≤–Ω–∏–∫ –∫–æ—Ç–∞ —É–±–∏–π—Ü—ã¬ª –≠–Ω–Ω –§–∞–π–Ω
    file: media/kot-ubiitsa.pdf
    tags:
      - –ø—Ä–∏–∫–ª—é—á–µ–Ω–∏—è
    description: '–ù–µ–≤–µ—Ä–æ—è—Ç–Ω–æ —Å–º–µ—à–Ω–∞—è –∫–Ω–∏–≥–∞ —Å –∏–Ω—Ç—Ä–∏–≥—É—é—â–∏–º –Ω–∞–∑–≤–∞–Ω–∏–µ–º. ¬´–î–Ω–µ–≤–Ω–∏–∫ –∫–æ—Ç–∞ —É–±–∏–π—Ü—ã¬ª –ø–æ–Ω—Ä–∞–≤–∏—Ç—Å—è –¥–∞–∂–µ —Å–∞–º—ã–º —é–Ω—ã–º —á–∏—Ç–∞—Ç–µ–ª—è–º. –í–æ-–ø–µ—Ä–≤—ã—Ö, —ç—Ç–æ —Å–±–æ—Ä–Ω–∏–∫ –∫–æ—Ä–æ—Ç–∫–∏—Ö –∏—Å—Ç–æ—Ä–∏–π, –∫–æ—Ç–æ—Ä—ã–µ –º–æ–∂–Ω–æ —á–∏—Ç–∞—Ç—å –≤ —Å–≤–æ–±–æ–¥–Ω–æ–º –ø–æ—Ä—è–¥–∫–µ. –í–æ-–≤—Ç–æ—Ä—ã—Ö, –ø–æ–≤–µ—Å—Ç–≤–æ–≤–∞–Ω–∏–µ –∑–¥–µ—Å—å –≤–µ–¥–µ—Ç—Å—è –æ—Ç –ª–∏—Ü–∞ —Ç–æ–≥–æ —Å–∞–º–æ–≥–æ –∫–æ—Ç–∞, –≤–µ–¥—å —ç—Ç–æ –¥–Ω–µ–≤–Ω–∏–∫, –∞ —á—Ç–æ –º–æ–∂–µ—Ç –±—ã—Ç—å –∑–∞–±–∞–≤–Ω–µ–µ, —á–µ–º —Ä–∞–∑–º—ã—à–ª–µ–Ω–∏—è –Ω–µ—É–≥–æ–º–æ–Ω–Ω–æ–≥–æ –¥–æ–º–∞—à–Ω–µ–≥–æ –ø–∏—Ç–æ–º—Ü–∞!

    –ù–∞ —Ä—É—Å—Å–∫–æ–º —è–∑—ã–∫–µ –∫–Ω–∏–≥–∞ –∏–∑–¥–∞–Ω–∞ —Å –ø–æ—Ç—Ä—è—Å–∞—é—â–µ —Å–º–µ—à–Ω—ã–º–∏ –∏–ª–ª—é—Å—Ç—Ä–∞—Ü–∏—è–º–∏, –∫–æ—Ç–æ—Ä—ã–µ –∏–Ω—Ç–µ—Ä–µ—Å–Ω–æ —Ä–∞–∑–≥–ª—è–¥—ã–≤–∞—Ç—å –∏ –æ–±—Å—É–∂–¥–∞—Ç—å.

    <b>–ö–æ–º—É –ø–æ–Ω—Ä–∞–≤–∏—Ç—Å—è —ç—Ç–∞ –∫–Ω–∏–≥–∞?</b>

    ‚Ä¢ –î–µ—Ç—è–º, –∫–æ—Ç–æ—Ä—ã–º –Ω—Ä–∞–≤–∏—Ç—Å—è —á–∏—Ç–∞—Ç—å –∫–æ—Ä–æ—Ç–∫–∏–µ –∏—Å—Ç–æ—Ä–∏–∏.

    ‚Ä¢ –ö–æ–Ω–µ—á–Ω–æ –∂–µ, –≤—Å–µ–º –ø–æ–∫–ª–æ–Ω–Ω–∏–∫–∞–º –∫–æ—Ç–æ–≤! –ù–∞–≤–µ—Ä–Ω—è–∫–∞ –æ–Ω–∏ –¥–∞–≤–Ω–æ –º–µ—á—Ç–∞–ª–∏ —É–∑–Ω–∞—Ç—å, –æ —á–µ–º –¥—É–º–∞—é—Ç –∏—Ö –ª—é–±–∏–º—Ü—ã.

    ‚Ä¢ –†–µ–±—è—Ç–∞–º, –≤—Å–µ –≤—Ä–µ–º—è –ø–æ–ø–∞–¥–∞—é—â–∏–º –≤ –∏—Å—Ç–æ—Ä–∏–∏. –û–Ω–∏ —É–∑–Ω–∞—é—Ç –≤ –≥–ª–∞–≤–Ω–æ–º –≥–µ—Ä–æ–µ —Å–µ–±—è.

    <b>–°—Å—ã–ª–∫–∏ –Ω–∞ –∫–Ω–∏–≥–∏:</b>

    <a href="https://www.ozon.ru/product/dnevnik-kota-ubiytsy-vse-istorii-299783677/?gclid=Cj0KCQiAr5iQBhCsARIsAPcwROO2hosED_d2yXl7RT5ZAXMex2NLVBMm-8IskI664_SczZPVcPR3OjoaAl7zEALw_wcB&sh=nYiB0wAAAA&utm_campaign=RF_Product_Shopping_Books_newclients_all_SSC&utm_medium=cpc&utm_source=google">–ü–µ—á–∞—Ç–Ω–∞—è –∫–Ω–∏–≥–∞</a>'

default_replay: I dont understand u.
reactions:
  - comand: /start
    replay: "–ü—Ä–∏–≤–µ—Ç! –Ø —Ä–∞–¥ —á—Ç–æ –≤—ã —Ä–µ—à–∏–ª–∏ –ø—Ä–∏—Å–æ–µ–¥–∏–Ω–∏—Ç—å—Å—è –∫ –Ω–∞–º. Bookgital ‚Äî —ç—Ç–æ —Å–µ—Ä–≤–∏—Å, –∫–æ—Ç–æ—Ä—ã–π –ø–æ–º–æ–≥–∞–µ—Ç –¥–µ—Ç—è–º –ø–æ–ª—é–±–∏—Ç—å —á—Ç–µ–Ω–∏–µ, –∞ —Ä–æ–¥–∏—Ç–µ–ª—è–º –≤—ã—Å—Ç—Ä–æ–∏—Ç—å –¥–æ–±—Ä—ã–π –¥–∏–∞–ª–æ–≥ –Ω–∞ —ç—Ç—É —Ç–µ–º—É.
    –ó–¥–µ—Å—å –≤—ã —Å–º–æ–∂–µ—Ç–µ –ø–æ–¥–æ–±—Ä–∞—Ç—å –∫–Ω–∏–≥–∏ –¥–ª—è —Å–≤–æ–∏—Ö –¥–µ—Ç–µ–π, –∏–∑—É—á–∏—Ç—å —Ä–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏–∏ –∏ —Å–æ–≤–µ—Ç—ã –æ—Ç –ø—Å–∏—Ö–æ–ª–æ–≥–æ–≤ –∏ —ç–∫—Å–ø–µ—Ä—Ç–æ–≤ –æ —Ç–æ–º, –∫–∞–∫ –≤—ã—Å—Ç—Ä–∞–∏–≤–∞—Ç—å –æ—Ç–Ω–æ—à–µ–Ω–∏—è —Ä–µ–±–µ–Ω–∫–∞ —Å –∫–Ω–∏–≥–∞–º–∏ –∏ –ø–æ–ª—É—á–∏—Ç—å –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç—ã –¥–ª—è –æ–±—Å—É–∂–¥–µ–Ω–∏—è –∫–Ω–∏–≥ —Å –¥–µ—Ç—å–º–∏. –ù–∞—á–Ω–µ–º?"
    buttons:
      - button: –ù–∞—á–∞—Ç—å
        callback: Q1||status:new #format: NEXT_CALLBACK_NAME||name1=value1,name2=value2,...
      - button: –ü–æ–∑–∂–µ
        callback: wait||status:new

callbacks:
  - name: wait
    text: –ë—É–¥–µ–º –∂–¥–∞—Ç—å, –∫–æ–≥–¥–∞ –≤—ã –±—É–¥–µ—Ç–µ –≥–æ—Ç–æ–≤—ã.
  - name: Q1
    text: '*–ß—Ç–æ–±—ã –º—ã –º–æ–≥–ª–∏ —Ä–µ–∫–æ–º–µ–Ω–¥–æ–≤–∞—Ç—å –∫–Ω–∏–≥—É, –Ω–∞–º –≤–∞–∂–Ω–æ —É–∑–Ω–∞—Ç—å —á—É—Ç—å –±–æ–ª—å—à–µ –æ –≤–∞—à–µ–º —Ä–µ–±–µ–Ω–∫–µ. –û—Ç–≤–µ—Ç—å—Ç–µ –Ω–∞ 3 –≤–æ–ø—Ä–æ—Å–∞:*
     
    *–°–∫–æ–ª—å–∫–æ –µ–º—É –ª–µ—Ç?*'
    buttons:
      - button: 8-9 ü¶¥
        callback: Q2||tag:Q1-1
      - button: 9-10 üëØ
        callback: Q2||tag:Q1-2
      - button: 10-11 üß∂
        callback: Q2||tag:Q1-3
      - button: 11-12 üëì
        callback: Q2||tag:Q1-4
  - name: Q2
    text: '–í–∞—à —Ä–µ–±–µ–Ω–æ–∫ —É–∂–µ –ª—é–±–∏—Ç —á–∏—Ç–∞—Ç—å?'
    buttons:
      - button: –Ω–µ—Ç
        callback: Q3||tag:Q2-1
      - button: –¥–∞
        callback: Q3||tag:Q2-2
  - name: Q3
    text: '–ö–∞–∫–∏–µ –∏–∑ —ç—Ç–∏—Ö —Ç–µ–º –±–ª–∏–∂–µ –≤–∞—à–µ–º—É —Ä–µ–±–µ–Ω–∫—É –∏–ª–∏ –±–æ–ª–µ–µ –∞–∫—Ç—É–∞–ª—å–Ω—ã —Å–µ–π—á–∞—Å?'
    buttons:
      - button: –î—Ä—É–∂–±–∞
        callback: ADVICE||tag:–¥—Ä—É–∂–±–∞,status:advice
      - button: –ò—Å—Ç–æ—Ä–∏–∏ –ø—Ä–æ –∂–∏–≤–æ—Ç–Ω—ã—Ö
        callback: ADVICE||tag:–∏—Å—Ç–æ—Ä–∏–∏ –ø—Ä–æ –∂–∏–≤–æ—Ç–Ω—ã—Ö,status:advice
      - button: –§–∞–Ω—Ç–∞–∑–∏–∏
        callback: ADVICE||tag:—Ñ–∞–Ω—Ç–∞–∑–∏–∏,status:advice
      - button: –û –≥–µ—Ä–æ—è—Ö –¥–µ–≤–æ—á–∫–∞—Ö
        callback: ADVICE||tag:–æ –≥–µ—Ä–æ—è—Ö –¥–µ–≤–æ—á–∫–∞—Ö,status:advice
      - button: –ü—Ä–∏–∫–ª—é—á–µ–Ω–∏—è
        callback: ADVICE||tag:–ø—Ä–∏–∫–ª—é—á–µ–Ω–∏—è,status:advice
  - name: ADVICE
    text: '–°–ø–∞—Å–∏–±–æ –∑–∞ –æ—Ç–≤–µ—Ç—ã! –°–µ–π—á–∞—Å –ø—Ä–∏—à–ª–µ–º –∫–Ω–∏–≥—É –∏ —Ñ–∞–π–ª —Å –ø—è—Ç—å—é –∫–∞—Ä—Ç–æ—á–∫–∞–º–∏: —ç—Ç–æ —Ç–µ–º—ã, –∫–æ—Ç–æ—Ä—ã–µ –ø–æ–º–æ–≥—É—Ç –≤–∞–º –æ–±—Å—É–¥–∏—Ç—å –ø—Ä–æ—á–∏—Ç–∞–Ω–Ω–æ–µ —Å —Ä–µ–±–µ–Ω–∫–æ–º, —Å—Ñ–æ—Ä–º–∏—Ä–æ–≤–∞—Ç—å –Ω–æ–≤—É—é –ø—Ä–∏–≤—ã—á–∫—É –∏ –ø—Ä–∏—è—Ç–Ω–æ –ø—Ä–æ–≤–µ—Å—Ç–∏ –≤—Ä–µ–º—è –≤–º–µ—Å—Ç–µ. –°–∫–∞—á–∞–π—Ç–µ —Ñ–∞–π–ª –∏ –ø–µ—Ä–µ–≤–µ—Ä–Ω–∏—Ç–µ —Ç–µ–ª–µ—Ñ–æ–Ω –≤ –≥–æ—Ä–∏–∑–æ–Ω—Ç–∞–ª—å–Ω—ã–π —Ñ–æ—Ä–º–∞—Ç, –¥–ª—è —É–¥–æ–±—Å—Ç–≤–∞.'
  - name: nothing
    text: Ok
  